API Truckload Support
azurestandard/api-spec pull request #291
Opened 2020-10-01 22:19 UTC by tompetersjr

Add support for a truckload concept to the API.

Fixes: #289

2020-10-01 22:32 UTC, igregson requested changes
Noticed two small description-related things.

2020-10-01 22:32 UTC, igregson commented on spec.json
> +            "description": "Array of truckload ID's. ",
Two things here: 
1. Since we've done so elsewhere, we should probably include "(pickset)" after "truckload"
2. There's a trailling space

2020-10-01 22:32 UTC, igregson commented on spec.json
> +            "description": "Array of truckloads. This will only be included if the `inline` query parameter includes `truckloads`.",
Since we've done so elsewhere, we should probably include "(picksets)" after "truckloads"

2020-10-01 22:38 UTC, igregson approved these changes

2020-10-01 23:38 UTC, davidmcatee-azure requested changes

2020-10-01 23:38 UTC, davidmcatee-azure commented on spec.json
> +          "truckloadIds"
Since `truckloadIds` will be not be present if the trip is not verified, I don't think it should be required. We may also want to mention this in the description for `truckLoadIds` above.

2020-10-01 23:38 UTC, davidmcatee-azure commented on spec.json
> +          "truckloadId"
Since `truckloadId` will be not be present if the stop's trip is not verified, I don't think it should be required. We may also want to mention this in the description for `truckLoadId` above.

2020-10-01 23:47 UTC, igregson commented on spec.json
> +          "truckloadIds"
I had understood that it would still be included, but set to `undefined`, no? Same for your point below.

2020-10-01 23:54 UTC, davidmcatee-azure commented on spec.json
> +          "truckloadIds"
That would be breaking from the API's existing pattern of not including such properties.

2020-10-02 16:28 UTC, davidmcatee-azure approved these changes

2020-10-15 21:53 UTC, davidmcatee-azure commented on spec.json
> +            "description": "For convenience, include additional information. Currently supports \"truckloadIds\" as described in the trip model."
Should be `truckloads` here, not `truckloadIds`.

2020-10-15 21:53 UTC, davidmcatee-azure commented on spec.json
> +            "description": "For convenience, include additional information. Currently supports \"truckloadIds\" as described in the trip model."
Should be `truckloads` here, not `truckloadIds`.

2020-10-16 19:44 UTC, davidmcatee-azure commented on spec.json
> +            "description": "ID of the truckload (pickset). This is only included if the trip is verified."
"This will only be included if the `inline` query parameter includes `truckloadId` and the trip is verified."

2020-10-16 20:01 UTC, igregson commented on spec.json
> +            "description": "ID of the truckload (pickset). This is only included if the trip is verified."
@tompetersjr Other than this, your changes look good to me.

2020-10-16 20:09 UTC, tompetersjr commented on spec.json
> +            "description": "ID of the truckload (pickset). This is only included if the trip is verified."
To make that statement true I need to make a change to the beehive PR [here](https://github.com/azurestandard/beehive/pull/5048/files#diff-61480bfff576892bbced73b51d655f951e9bd1131930996a06f53fe6d510f44dR40-R44).  I'll make that change as well.

2020-10-16 20:30 UTC, igregson commented on spec.json
> +            "description": "ID of the truckload (pickset). This will only be included if the inline query parameter includes truckloadId and the trip is verified."
Based on formatting elsewhere in the spec, "truckloadId" here should either be in double quotes or backticks (it seems we're not consistent with which of these we prefer, so either would be fine for now, IMO).

2020-10-19 21:04 UTC, igregson approved these changes

2020-10-20 18:29 UTC, igregson commented
This had merge conflicts due to #293. For some reason the way I was resolving them kept breaking things but I think it's now (finally) right. @tompetersjr / @davidmcatee-azure want to give this another quick look before we merge it?

2020-10-20 18:33 UTC, tompetersjr commented
Looks good to me.

2020-10-20 18:36 UTC, merged

2020-10-20 18:37 UTC, davidmcatee-azure approved these changes