Add drops/actions/convert-route endpoint
azurestandard/api-spec pull request #295
Opened 2020-10-20 00:39 UTC by igregson

Resolves #283

2020-10-20 00:47 UTC, igregson commented
Wasn't sure who to request a review from for this. Went with you, David, since you've generally reviewed my previous API-Spec PRs. Since you worked on this code in the backend, Tom, thought maybe that your review on it would also/instead be appropriate.

2020-10-20 00:52 UTC, davidmcatee-azure requested changes

2020-10-20 00:52 UTC, davidmcatee-azure commented on spec.json
> +            "description": "A comma-separated list of the IDs of drops to be moved."
According to the code, `dropIds` is not a comma-separated list of ids, but rather an array of ids.

2020-10-21 16:36 UTC, davidmcatee-azure requested changes

2020-10-21 16:36 UTC, davidmcatee-azure commented on spec.json
> +            "in": "query",
Just noticed that these parameters should be in the request body, not the query parameters.

2020-10-21 17:08 UTC, igregson commented on spec.json
> +            "in": "query",
🤦 

Good catch. Fixed.

2020-10-21 18:37 UTC, davidmcatee-azure approved these changes

2020-10-21 18:58 UTC, merged