added the parcelCarrierShipByDate field to the spec for updateOrder
azurestandard/api-spec pull request #304
Opened 2020-12-21 20:25 UTC by dwmorrison33

This is for the latest code in PR: https://github.com/azurestandard/beehive/pull/5188 

@igregson I could not remember how to update this spec in the UI of https://azurestandard.stoplight.io/docs/api-spec/public.yaml so I just modified the code manually in the spec.json to add the field that is now getting returned in the `updateOrder` endpoint.

2020-12-21 21:47 UTC, igregson commented
> I could not remember how to update this spec in the UI of https://azurestandard.stoplight.io/docs/api-spec/public.yaml so I just modified the code manually in the spec.json [...]

No worries. Doesn't matter if you use Stoplight or not, which is the beauty of the workflow we've adopted.

2020-12-21 21:48 UTC, igregson requested changes
Looks like we should also add `parcelCarrierShipByDate` to the `order` return object, no?

2020-12-21 21:58 UTC, dwmorrison33 commented
> Looks like we should also add parcelCarrierShipByDate to the order return object, no?

@igregson You are correct, I have updated it.

2020-12-21 22:14 UTC, igregson commented on spec.json
> +            "format": "date"
I'm pretty sure the `format` (here and below) should be `date-time`.

2020-12-21 22:22 UTC, dwmorrison33 commented on spec.json
> +            "format": "date"
It is a date, not a datetime

2020-12-21 22:23 UTC, igregson commented on spec.json
> +            "format": "date"
Hmm... I remember seeing a date with a time (in ISO format) returned by the API (while @davidmcatee-azure was demoing this for me).

2020-12-21 22:24 UTC, dwmorrison33 commented on spec.json
> +            "format": "date"
Here is a reference: https://github.com/azurestandard/beehive/pull/5188#issuecomment-747064555

2020-12-21 22:35 UTC, igregson commented on spec.json
> +            "format": "date"
The value that the frontend will be setting for this ([here](https://github.com/azurestandard/website/blob/dm/parcel-carrier-ship-by/src/core/services/app_state.js#L666)) includes the time. The value comes from what the API returns as a `next-purchase-arrival` (on the `packaged-products` endpoint, though the response value here in the spec looks like it's missing this – I'll create a PR for that).

2020-12-22 02:18 UTC, igregson commented on spec.json
> +            "format": "date"
(I've created the PR for adding `next-purchase-arrival` to the `packaged-products` endpoint. Note that it's a `date-time`. See https://deploy-preview-305--azure-api-docs.netlify.app/#operation/findPackagedProduct)

2020-12-22 13:35 UTC, dwmorrison33 commented on spec.json
> +            "format": "date"
@davidmcatee-azure When we discussed this last week, we agreed that the field would be a `DateField` in Django and the code was written with that requirement. Has something changed where this is supposed to be a `DateTimeField` now?

2020-12-22 16:42 UTC, davidmcatee-azure commented on spec.json
> +            "format": "date"
Since only the date matters, it makes sense to store it as a `DateField`. As far as the API is concerned, I mentioned that I wanted it in ISO ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)) format because that would be the easiest for JavaScript to handle. These requirements are not incompatible. "2020-12-22" is valid as is "2020-12-22T16:13:04+00:00". I think keeping `"format": "date"` in the API spec would be OK. We happen to set it using a date with a time, but the time will portion of it will be dropped (this detail could be added to the description to clear up confusion).

2020-12-22 17:08 UTC, igregson commented on spec.json
> +            "format": "date"
> [...] this detail could be added to the description to clear up confusion

@dwmorrison33 Could you do this?

2020-12-22 17:23 UTC, dwmorrison33 commented on spec.json
> +            "format": "date"
Yes, I updated it and pushed the code up

2020-12-22 17:24 UTC, igregson commented on spec.json
> +            "format": "date"
Perfect! Thank you :)

2020-12-22 17:25 UTC, igregson approved these changes

2020-12-22 17:27 UTC, davidmcatee-azure approved these changes

2020-12-23 13:39 UTC, merged

2020-12-23 13:40 UTC, dwmorrison33 commented
@igregson I have merged this into master. I am gonna close this PR, but I am unsure how to deploy these updates to Spotlight.

2021-01-04 17:28 UTC, igregson commented
> I am unsure how to deploy these updates to Spotlight

There is nothing to deploy to Stoplight.