Picksets-Trucks api initial defintions
azurestandard/api-spec pull request #321
Opened 2021-06-24 19:40 UTC by tommckennon

2021-06-24 20:09 UTC, tommckennon commented on spec.json
> +          },
Note: This is a little deceiving in GitHub, but this is under the /people endpoint definition.

2021-06-24 21:02 UTC, davidmcatee-azure requested changes

2021-06-24 21:02 UTC, davidmcatee-azure commented on spec.json
> +            "name": "customerTypes",
It would be simpler at first to make this filter by a single `customerType`. When allowing multiple, there are two ambiguities that are introduced. One is whether the multiple filters function as an AND vs. an OR (it could be either since this is a many-to-many relationship). The other is how the multiple values are serialized/deserialized. Both ambiguities would need to be clearly defined and it doesn't make sense to go through all that when all we currently need is to filter by one type, i.e. "truck-driver".

2021-06-24 23:36 UTC, tommckennon commented on spec.json
> +    "/trucks": {
Hey David. I want to make sure of this. Perhaps trucks is the wording to use here. I'm seeing that the "truckloads" synonym is already being used in the api for the internal website here: https://github.com/azurestandard/api-spec/blob/28dae5fce84c35f9b1d3178917b5cdac80f439c7/spec.json#L12993

2021-06-24 23:53 UTC, tommckennon commented on spec.json
> +    "/trucks": {
Tom mentioned here https://github.com/azurestandard/beehive/pull/5603#discussion_r658075697 we were planning to have the truck drivers be apart of the already defined "truckloads" and want to instead make them apart of the new trucks api if I'm reading that correctly. But I may be misinterpreting, so seeking confirmation this should not be "trucks" before changing to "truckloads".

2021-06-25 00:04 UTC, davidmcatee-azure commented on spec.json
> +    "/trucks": {
This "truckload" is the same thing as what you are implementing; "truckloads" is a synonym for "picksets". Currently the only way truckloads are exposed to the frontend is if you inline them on a /trips request using `inline=truckloads` or on a /stops request using `inline=truckload`. The new endpoint `/truckloads` is the first-class Plural endpoint for the same resource. As I mentioned in another spot, we don't actually need this Plural endpoint right now since we are inlining the truckloads in both our queries to /trips and /stops (an alternative implementation without using the inline parameter could use separate queries to the Plural truckloads endpoint filtering for a particular trip or stop, but it was decided in the initial implementation of truckload support to take a shortcut and only implement the inline support rather than make the first-class endpoint for truckloads). What we do need is a `put` endpoint for the Singular `/truckload/{id}` due to the fact that we need to be able to update the driver on a truckload from the frontend.

2021-06-25 00:05 UTC, davidmcatee-azure commented on spec.json
> +    "/trucks": {
It is the Singular `put` that is necessitating the creating of the first-class /truckloads endpoint. But it is the same thing as the "truckloads" that already exists in the spec.

2021-06-25 00:07 UTC, tommckennon commented on spec.json
> +          }
That makes sense. Will remove those. Actually, after thinking about it, I think the first filter would be a filter on route_trip to get the pick sets of the route trip, but not sure if it's needed based on what's already being pulled into logistics. Will add route_trip if making that query makes sense somewhere in the workflow.

2021-06-25 00:09 UTC, davidmcatee-azure commented on spec.json
> +          }
> but not sure if it's needed based on what's already being pulled into logistics

Right, this relates to my explanation of why it should be "truckloads". The reason it's not needed is because we're already inlining the truckloads in our /trips request.

2021-06-25 00:12 UTC, tommckennon commented on spec.json
> +    "/trucks": {
I see. Understood. It makes sense to match it to how it's already defined in this api under trips, which makes "truckloads" the correct term. Thanks. Changing.

2021-06-25 00:47 UTC, tommckennon commented on spec.json
> +            "name": "customerTypes",
There's no question we will be adding more, so I think we'd want this to stay. I've handled many to many relationships by always passing an array of values to filter on with an array length of 1 for one value to filter on, since the relationship is not equal to a singular value (always an array of values).

2021-06-25 00:56 UTC, davidmcatee-azure commented on spec.json
> +            "name": "customerTypes",
We may be adding more customer types, but I am questioning whether we have a use case for filtering on more than one. If not, then I would start with implementing filtering by a single `customerType`. If we have a use case arise later to filter on multiple, then we can update accordingly. The parameter name should be `customerType` either way (not the plural `customerTypes`). In other places where we have query parameters that accept multiple values, the singular form is still used.

2021-06-25 01:03 UTC, tommckennon commented on spec.json
> +            "name": "customerTypes",
I follow. That's the one facet of the api I've done differently on my end semantically, but the reasoning and approach you mention works for me...changing.

2021-06-25 01:08 UTC, tommckennon commented
Thank you for covering all the detailed fixes for these api additions. It puts me in position to put forth a PR for the corresponding API provider updates.

2021-06-25 16:59 UTC, davidmcatee-azure commented on spec.json
> +          "truckDriverId"
If `"truckDriverId"` is required, then you could not do a PUT with an empty `truckDriverId` to remove the truck driver from the truckload. In other words, once a truck driver is assigned, you can only change the truck driver, you cannot remove. I don't think we had clear requirements on this aspect. It is a bit restrictive on the user to not allow removal (what if they accidentally assigned a truck driver prematurely, and wanted to undo it?) However, since we don't have clear requirements there, I would be OK with requiring `truckDriverId`, but then your backend implementation should match. I will comment accordingly.

2021-06-25 17:29 UTC, tommckennon commented on spec.json
> +          "truckDriverId"
Understood. Did so on the updates to https://github.com/azurestandard/beehive/pull/5603

2021-06-25 18:08 UTC, davidmcatee-azure commented on spec.json
> +        "description": "Truckloads (picksets) are ordered by truck number.",
It looks like your implementation uses the default `PickSet` ordering of `"route_trip__pull", "sequence", "truck_number"`. I don't think this description adequately reflects that, but I'm also not sure how to translate that into English because I don't know what "sequence" is. This would at least be closer:

> "Truckloads (picksets) are ordered by the associated trip's pick date and then truck number."


>

2021-06-25 19:17 UTC, davidmcatee-azure commented on spec.json
> +          }
You can remove `route-trip`, `truck-number`, and `pick-date` since we are not currently allowing those to be updated via the API.

2021-06-25 21:08 UTC, davidmcatee-azure approved these changes

2021-06-25 21:09 UTC, merged