Get Product Fixes
azurestandard/api-spec pull request #323
Opened 2021-07-14 00:31 UTC by tommckennon

2021-07-14 00:35 UTC, tommckennon commented
Order fixed as well as to match how these properties are returned from the api.

2021-07-14 04:06 UTC, tommckennon commented
I also ordered these properties to match how they are specified on the backend. I think it makes it easier to follow what properties are defined for the api whether baseline or inline.

2021-07-14 19:52 UTC, davidmcatee-azure requested changes

2021-07-14 19:52 UTC, davidmcatee-azure commented on spec.json
> +            "description": "Sentence-length product name (either its given name or marketing name).",
From the API consumer's perspective, the distinction between given name or marketing name does not matter. I think this edit should be reverted.

2021-07-14 19:52 UTC, davidmcatee-azure commented on spec.json
>              "type": "string"
It seems to me this can be kept as `"$ref": "#/components/schemas/storage"`.

2021-07-14 19:52 UTC, davidmcatee-azure commented on spec.json
> +            "description": "If true, this product will can be shipped by UPS.",
"If true, this product can be shipped by parcel carrier."

2021-07-14 19:52 UTC, davidmcatee-azure commented on spec.json
> +              "format": "int64"
Should be:
`"$ref": "#/components/schemas/packagedProduct"`

2021-07-14 19:52 UTC, davidmcatee-azure commented on spec.json
> +            "description": "Comma-separated list of keywords that will be used in Google web search for this specific product. This will only be included if the `inline` query parameter includes `key
Suggest simplifying to:
"Comma-separated list of keywords for this product. This will only be included if the `inline` query parameter includes `keywords`."

2021-07-14 19:52 UTC, davidmcatee-azure commented on spec.json
> +            "description": "Long-form, HTML product description. When short-description is set, this value is for additional information which did not fit into short-description. Displaying both shor
Replace all instances of "short-description" with `shortDescription`.
For example: " ... When `shortDescription` is set ... "

2021-07-14 19:52 UTC, davidmcatee-azure commented on spec.json
> +              }
Should reference existing vendor schema:
```
                  "items": {
                    "$ref": "#/components/schemas/vendor"
                  }
```

2021-07-15 04:36 UTC, tommckennon commented on spec.json
>              "type": "string"
This one (storageClimate) is returning just a string: https://github.com/azurestandard/beehive/blob/ada64c39d27cebc87ec1d99124c98934a252cc28/apps/api/views/product.py#L51

2021-07-15 05:37 UTC, davidmcatee-azure commented on spec.json
>              "type": "string"
`"$ref": "#/components/schemas/storage"` refers to this:

https://github.com/azurestandard/api-spec/blob/tm/get-product-fixes/spec.json#L10482-L10491

... which is a string. It can only have 4 values: "dry", "chilled", "frozen", or "greenhouse".

2021-07-15 05:40 UTC, davidmcatee-azure commented on spec.json
> +            "description": "Long-form, HTML product description. When shortDescription is set, this value is for additional information which did not fit into shortDescription. Displaying both shortD
Each instance of `shortDescription` should be enclosed in backticks.

2021-07-16 12:46 UTC, tommckennon commented on spec.json
>              "type": "string"
I see. Ready for review.

2021-07-16 16:32 UTC, davidmcatee-azure commented on spec.json
> +            }
This should be:
```
          "storageClimate": {
            "$ref": "#/components/schemas/storage"
          },
```

2021-07-16 16:44 UTC, davidmcatee-azure commented on spec.json
> +            "$ref": "#/components/schemas/storage"
You can also remove the description since the ref has its own description and it is the one that is displayed in redoc.

2021-07-16 17:13 UTC, davidmcatee-azure approved these changes

2021-07-16 17:14 UTC, merged