Add order lines to API Spec
azurestandard/api-spec pull request #324
Opened 2021-08-30 15:56 UTC by etmartinkazoo

This adds customer and internal notes to the API Spec.

2021-08-30 16:22 UTC, davidmcatee-azure requested changes
A general question: Is the UI for entering internal notes going to be the website in superuser mode?

2021-08-30 16:22 UTC, davidmcatee-azure commented on spec.json
> +            "type": "string"
Can you make these camelCase please?

2021-08-30 16:22 UTC, davidmcatee-azure commented on spec.json
> +          "internal-note"
I don't think these should be required. If there aren't any notes, they would be omitted.

2021-08-30 16:29 UTC, etmartinkazoo commented on spec.json
> +            "type": "string"
@davidmcatee-azure - Yes, I've changed to camelCase and committed.

2021-08-30 16:30 UTC, etmartinkazoo commented on spec.json
> +          "internal-note"
Thank you, yes you are right. Removed and committed.

2021-08-30 16:30 UTC, etmartinkazoo commented
> A general question: Is the UI for entering internal notes going to be the website in superuser mode?

Yes, superusers will be able to enter internal notes on the website.

2021-08-30 17:03 UTC, davidmcatee-azure approved these changes

2021-09-10 16:22 UTC, etmartinkazoo commented
@davidmcatee-azure - For the API spec is it sufficient to merely `Merge` the PR into master or is there more to do vis a vis deployment?

2021-09-10 18:10 UTC, tommckennon approved these changes

2021-09-10 18:32 UTC, davidmcatee-azure commented
> @davidmcatee-azure - For the API spec is it sufficient to merely `Merge` the PR into master or is there more to do vis a vis deployment?

Just merging to master here. I can do so.

2021-09-10 18:33 UTC, merged